version: '3.8'

services:
  backend:
    build: .
    stdin_open: true
    tty: true
    environment:
      EXPO_USE_STDIN: "1"
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: Jatin11
      DB_NAME: ai_image_generator
      NODE_ENV: development
    ports:
      - "8000:8000"
      - "8081:8081"
    depends_on:
      - mysql
    volumes:
      - ./backend:/app/backend
      - ./screens:/app/screens
      - ./package.json:/app/package.json
      - ./app.json:/app/app.json
      - ./assets:/app/assets
      - ./backend/data:/app/data

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Jatin11
      MYSQL_DATABASE: ai_image_generator
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  mysql_data:
